### ISSUE TITLE
missing deps

### ISSUE THREAD

**Issue by nikita-fuchs** [kozmoz/node-dymo-printer#2]
hey, thanks for the this. WHen trying to run a demo, there seems to be some missing dependency ? 

```
✘ [ERROR] Could not resolve "node-dymo-printer"

    demo1.ts:1:52:
      1 │ const {DymoServices, createImageWithText} = require('node-dymo-printer');
        ╵                                                     ~~~~~~~~~~~~~~~~~~~

  The module "./dist/cjs/dymo-services.js" was not found on the file system:

    package.json:11:17:
      11 │       "require": "./dist/cjs/dymo-services.js"
```

**Comment by kozmoz** [comment]
To use node-dymo-printer in your Node project, you first need to install it as a module. It also doesn't run in the browser.

I have updated the README.md file to provide further clarification on this process.

**Comment by nikita-fuchs** [comment]
thanks!
